### ISSUE TITLE
 Large size of a file named "ARIALUNI.TTF"

### ISSUE THREAD

**Issue by ashishsureka** [ashishsureka/cruise#1]
There is a file named "ARIALUNI.TTF" in the fonts folder which is **22.1 MB** - Just this single file is 33% of the entire application? What is its purpose and do we really need it (is there a light-weight alternative)? We don't want the code to contain elements which are very large and not required.

**Comment by ashishsureka** [comment]
This file is the package of the all the arial family font files. This is for future use if font needs to be changed from same font family. You can delete one if you feel it is a big file.

**Comment by Pinorabo** [comment]
I have a ttf file of 10 Go, can please someone explain to me why it is that big ???
