### ISSUE TITLE
Table creation and reset scripts needed

### ISSUE THREAD

**Issue by ashishsureka** [ashishsureka/cruise#2]
I have created the 17 tables based on the SQL dump and deleted all past data.   We should not create a new installation from an SQL dump and should have scripts to create all tables (with 0 rows) and a script to delete all the data in tables but not the tables (reset)
-   Need an SQL script to create 17 empty tables
-   Need an SQL script to reset/empty all 17 tables

**Comment by Winspire** [comment]
Reset Tables Link : cruise-platform.in/admincp/tables_trucate

few tables cannot be truncated due to those data we have to keep in that for website basic information and requirements.

**Comment by Winspire** [comment]
Create Tables Link : cruise-platform.in/admincp/tables_create
