### ISSUE TITLE
Dashboard page after first login

### ISSUE THREAD

**Issue by ShRicha** [ashishsureka/cruise#6]
When a new user logs in to the application, the user cannot create a new project as 'Create Project' button is not available to him. In this way, a new user cannot just proceed to do anything. Suggestion is to display 'Create Project' button and an empty project list.

![dashboard-firstlogin](https://cloud.githubusercontent.com/assets/18419189/20647560/50b464fa-b4bd-11e6-83c0-e0d5f5753cc1.png)

When one or more project (s) is/are created , then restore the page having all the buttons as decided earlier. A screenshot from the previous version is here:

![dashboard 1](https://cloud.githubusercontent.com/assets/18419189/20647647/bbb08856-b4bd-11e6-8de4-c6292cb38f3a.png)

**Comment by Winspire** [comment]
All things are done. currently all database tables are empty so initially you have to create projects and users from admin panel

**Comment by ShRicha** [comment]
Is the fix available on http://wwsptech.com/projects16/cruise/login or,

http://www.cruise-platform.in/

On the former one, there are already projects by username : sricha  so cannot test there!

On the latter one, I cannot register as probably tables have been cleaned from there! I have submitted query form but not sure to which mail-id currently query form information is directed to. Please help with testing this defect!

**Comment by Winspire** [comment]
You can receive email by updating your email settings from this page :

http://cruise-platform.in/admincp/emailsetting

their is a field name as "admin email" which is for receiving mail in your email-id

**Comment by ShRicha** [comment]
Aniket, the problem is still the same. After login, a new user cannot do anything:

![current dashboard - first login](https://cloud.githubusercontent.com/assets/18419189/20919851/bfaa9c00-bbc3-11e6-9abb-f624ce2a9ef2.png)

If the user cannot create project, then he can't proceed further. Please treat this urgent!

**Comment by Winspire** [comment]
It is compulsory to assign project. As an uninvited user, one cannot create new project. As per scope the user has to be invited for atleast one project. We have added one field of Select project in add user form.

**Comment by ShRicha** [comment]
Aniket, we had a change in between. Earlier we had denied project creation from external user. In fact, we had not considered external registration. But, later on, we felt that it is quite possible that some user finds CRUISE tool of use to him/her and that person seeks access from admin to CRUISE. The admin is supposed to look at the person's background and allow/deny the access to this person. Now, it is possible that admin may or may not allocate him to project. Not allocation case will happen when the person does not express interest to contribute to a particular project while contacting the CRUISE administrators. A good solution to this problem would be - show an empty project list with only 'Create Project'. This is the first page. When one project has been created then the page with all buttons should appear.

Please make sure that in case admin has assigned a project to an invited new user, then this new user should be able to view the assigned project. I am emphasizing this so that fixing one defect won't affect the existing functionality! 

Please let me know if there is still any doubt.

**Comment by Winspire** [comment]
![untitled](https://cloud.githubusercontent.com/assets/22490073/20963662/51076a7c-bc94-11e6-94a9-419830060dce.png)
Now new user can also create new project

**Comment by ShRicha** [comment]
This looks good now!
