### ISSUE TITLE
Minor Concerns

### ISSUE THREAD

**Issue by ShRicha** [ashishsureka/cruise#7]
1. On the dashboard page, the project overview is not coming correctly. In the attached screen-shot (Dashboard - Project List - 1.png), for the first project - 'Meeting room booking', one of the modules is appearing instead of project overview. For the second project, the field - project overview is appearing as blank.
![dashboard - project list - 1](https://cloud.githubusercontent.com/assets/18419189/21470553/3b15214a-cab4-11e6-9400-ebfb2836d193.png)

2. There are 3 categories of projects - 'Projects you own', 'Projects as contributor' and 'Other projects'. Please correct label for first category. It is appearing as 'Projects your own' - it should be 'Projects you own'.

3. User - Richa created two projects - Meeting Room Booking and Mobile App for room-booking. The project -  Library Management System was created by user RS. But, this project did not appear as other project in user - Richa project list until user RS sent an invite for the same.
  Actually, the Library Management System should have appeared as 'other project' in user - Richa project list. If user Richa wants to contribute to this project, then that user can select this project and click 'Contribute' button. Then this project will appear under - ''Projects as contributor' list of user - Richa. Please check attached screen-shot - Dashboard - Project List - 2.

4. When user RS sent an invite to user Richa (who is already registered on CRUISE), again an invitation is sent to user Richa to login/register. I think this message is configurable from admin dashboard, please confirm.
![dashboard - project list - 2](https://cloud.githubusercontent.com/assets/18419189/21470591/f6b81a50-cab5-11e6-9d6e-e255b7103c22.png)

**Comment by Winspire** [comment]
1. currently we are giving module details(module title & module description) in project overview as given in finalised design. but if you want project description in it then there will be no title in project overview column.

2. Done

3. As it is closed forum and as in discussion about project their is no scope to display any project to uninvited user.

4. Done

**Comment by ShRicha** [comment]
Well! that is not the case. Anyways, I'll close it.
