### ISSUE TITLE
Screen Refresh

### ISSUE THREAD

**Issue by ShRicha** [ashishsureka/cruise#8]
Screens are getting refreshed even after 'Cancel' button or 'Close' button click after viewing project, module or requirement. I think at the click of these buttons, screen refresh is not required.

**Comment by Winspire** [comment]
I did stopped of page refresh on "view requirement" and "view module". 

in other situations it is required to make page refresh because if anyone enter text in model text box and close that model and open it in another record then it will display previously returned text in the same text box.
