### ISSUE TITLE
Enhancement for 'View requirements Details'

### ISSUE THREAD

**Issue by ShRicha** [ashishsureka/cruise#9]
Can we have following details in 'View requirements details' window:

1. Number of likes (i.e. count / summary)
2. Number of dislikes (i.e. count / summary)
3. Number of counts (i.e. count / summary)

**Comment by Winspire** [comment]
Please describe your requirements in brief.

Specially describe about which kind of summary you required.

The number of counts of "likes & dislikes" are already been there 

![screenshot-localhost-2016-12-26-14-57-46](https://cloud.githubusercontent.com/assets/22490073/21479650/1033715c-cb7c-11e6-9b94-42b91e118385.png)

**Comment by ShRicha** [comment]
We would like to have such a summary only - counts/total number of likes and dislikes for a requirement and also total number of comments for that requirement. However, it is not there currently, I am sharing screen-shot of requirements for one project where in I have added likes and dislikes as below:

The screen-shot that you have posted is from admin's site. But, I don not see any such screen there as well!
![requirements list-1](https://cloud.githubusercontent.com/assets/18419189/21480720/ba6e8388-cb85-11e6-9417-09630d085883.png)

**Comment by Winspire** [comment]
Counts added. 
See attachment

![c1](https://cloud.githubusercontent.com/assets/22490073/21500836/e0c0e650-cc68-11e6-912d-573a77b37036.JPG)

![screenshot-cruise-platform in-2016-12-28-10-00-03](https://cloud.githubusercontent.com/assets/22490073/21513954/bc842f96-cce4-11e6-9361-66e631b78597.png)
